sonar.projectKey=devops-cloud-hub
sonar.projectName=DevOps & Cloud Master Platform
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.sourceEncoding=UTF-8
